name: terraform-plan

on:

  workflow_dispatch:
  

jobs:

  terraform-plan:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    env:

         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

         AWS_DEFAULT_REGION: us-east-1
         TF_TOKEN: ${{secrets.tf_token}}
         TF_APP_PASS: ${{secrets.tf_app_pass}}
    steps:
      - name: checkout files from Infra-repo
        uses: actions/checkout@v3
        with:
          repository: Sundharabalaji-1Cloudhub/Infra-repo
          token: ${{secrets.pat_token}}

      - name: Setup Terraform

        uses: hashicorp/setup-terraform@v2

 
      - uses: terraform-linters/setup-tflint@v4

        name: Setup TFLint

        with:

         tflint_version: v0.50.3
 
  

      - name: checking syntax with tflint

        run: | 
              tflint --init
              tflint -f compact
              

        continue-on-error: true

      - name: Setup OPA

        uses: open-policy-agent/setup-opa@v2

        with:

         version: latest
 
      - name: testing policies with OPA

        run: opa test . || true
 
      - name: analysing with tfsec

        uses: aquasecurity/tfsec-action@v1.0.0

        with:

          soft_fail: true

     
      - name: analysing with checkov

        uses: bridgecrewio/checkov-action@v12

        with:
          soft_fail: true 
          quiet: true 

      - name: Terraform init
        run: terraform init -reconfigure  -backend-config="./backend.tfvars"

      - name: Terraform plam
        run: |
            terraform plan -auto-approve \
            -var="tf_token=${TF_TOKEN}" \
            -var="tf_app_pass=${TF_APP_PASS}" 

